services:
  backend:
    build:
      context: backend
    volumes:
      - ./database:/app/db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
    ports:
      - "80:80"
