/**
 * Defines the available entities in a BMC canvas.
 */
export enum BmcEntity {
  PARTNERS = "PARTNERS",
  ACTIVITIES = "ACTIVITIES",
  RESOURCES = "RESOURCES",
  PROPOSITIONS = "PROPOSITIONS",
  RELATIONSHIPS = "RELATIONSHIPS",
  CHANNELS = "CHANNELS",
  CUSTOMERSEGMENTS = "CUSTOMERSEGMENTS",
  COSTSTRUCTURE = "COSTSTRUCTURE",
  REVENUESTREAMS = "REVENUESTREAMS",
}
