/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enum of all the different entities a canvas contains.
 */
export type BmcEntity = 'PARTNERS' | 'ACTIVITIES' | 'RESOURCES' | 'PROPOSITIONS' | 'RELATIONSHIPS' | 'CHANNELS' | 'CUSTOMERSEGMENTS' | 'COSTSTRUCTURE' | 'REVENUESTREAMS';

export const BmcEntity = {
    Partners: 'PARTNERS' as BmcEntity,
    Activities: 'ACTIVITIES' as BmcEntity,
    Resources: 'RESOURCES' as BmcEntity,
    Propositions: 'PROPOSITIONS' as BmcEntity,
    Relationships: 'RELATIONSHIPS' as BmcEntity,
    Channels: 'CHANNELS' as BmcEntity,
    Customersegments: 'CUSTOMERSEGMENTS' as BmcEntity,
    Coststructure: 'COSTSTRUCTURE' as BmcEntity,
    Revenuestreams: 'REVENUESTREAMS' as BmcEntity
};

