/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';
import { LoginRequest } from '../model/models';
import { RegistrationRequest } from '../model/models';
import { Token } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApiAuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login For Access Token
     * Login endpoint which returns an access token for valid login credentials.
     * @param loginRequest 
     */
    loginForAccessTokenApiLoginPost(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<Token>;

    /**
     * Register User
     * User registration endpoint
     * @param registrationRequest 
     */
    registerUserApiRegisterPost(registrationRequest: RegistrationRequest, extraHttpRequestParams?: any): Observable<User>;

}
