/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BmcEntry } from '../model/models';
import { Canvas } from '../model/models';
import { CreateCanvasRequest } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CanvasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Canvas
     * Creates a new canvas under the name of the user.
     * @param createCanvasRequest 
     */
    createCanvasApiCanvasPost(createCanvasRequest: CreateCanvasRequest, extraHttpRequestParams?: any): Observable<Canvas>;

    /**
     * Get Canvas Entries
     * Returns all canvas entries for the canvas if the user can access it.
     * @param canvasId 
     */
    getCanvasEntriesApiCanvasCanvasIdEntriesGet(canvasId: number, extraHttpRequestParams?: any): Observable<Array<BmcEntry>>;

    /**
     * Get User Canvases
     * Returns all canvases a user has created.
     */
    getUserCanvasesApiUserCanvasesGet(extraHttpRequestParams?: any): Observable<Array<Canvas>>;

}
